// <auto-generated />
using System;
using ExifApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExifApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329142550_IntroduceSession")]
    partial class IntroduceSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("ExifApi.Data.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Hexagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("H3Index")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("H3Index")
                        .IsUnique();

                    b.ToTable("Hexagons");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Heading")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HexagonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HexagonId");

                    b.HasIndex("SessionId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.RoadTurbulence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HexagonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HexagonId");

                    b.HasIndex("SessionId");

                    b.ToTable("RoadTurbulences");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.RoadVisualAnomaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxX1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxX2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxY1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxY2")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HexagonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HexagonId");

                    b.HasIndex("ImageId");

                    b.ToTable("RoadVisualAnomalies");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxX1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxX2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxY1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxY2")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HexagonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HexagonId");

                    b.HasIndex("ImageId");

                    b.HasIndex("SessionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Image", b =>
                {
                    b.HasOne("ExifApi.Data.Entities.Hexagon", "Hexagon")
                        .WithMany()
                        .HasForeignKey("HexagonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExifApi.Data.Entities.Session", "Session")
                        .WithMany("Images")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hexagon");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.RoadTurbulence", b =>
                {
                    b.HasOne("ExifApi.Data.Entities.Hexagon", "Hexagon")
                        .WithMany("Turbulences")
                        .HasForeignKey("HexagonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExifApi.Data.Entities.Session", "Session")
                        .WithMany("RoadTurbulences")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hexagon");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.RoadVisualAnomaly", b =>
                {
                    b.HasOne("ExifApi.Data.Entities.Hexagon", "Hexagon")
                        .WithMany("Anomalies")
                        .HasForeignKey("HexagonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExifApi.Data.Entities.Image", "Image")
                        .WithMany("Anomalies")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hexagon");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Session", b =>
                {
                    b.HasOne("ExifApi.Data.Entities.Agent", "Agent")
                        .WithMany("Sessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Vote", b =>
                {
                    b.HasOne("ExifApi.Data.Entities.Hexagon", "Hexagon")
                        .WithMany("Votes")
                        .HasForeignKey("HexagonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExifApi.Data.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExifApi.Data.Entities.Session", "Session")
                        .WithMany("Votes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hexagon");

                    b.Navigation("Image");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Agent", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Hexagon", b =>
                {
                    b.Navigation("Anomalies");

                    b.Navigation("Turbulences");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Image", b =>
                {
                    b.Navigation("Anomalies");
                });

            modelBuilder.Entity("ExifApi.Data.Entities.Session", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RoadTurbulences");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
